In [1]:
import pickle

In [2]:
from tqdm import tqdm

In [3]:
import os

In [4]:
from collections import Counter

In [5]:
import re

In [6]:
import numpy as np

In [7]:
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk import ngrams
from pymystem3 import Mystem

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
files = os.listdir('./data')

In [7]:
files[-1]

'229754.title'

In [19]:
dc = {}
with open('./total.dict', 'rb') as fin:
    dc = pickle.load(fin)

In [22]:
len(dc)

12708700

In [8]:
nums = list(map(lambda x: int(x.split('.')[0]), os.listdir('data/')))

In [11]:
max(nums)

191327

In [20]:
len(ds)

1890036

In [53]:
ds = set()

In [54]:
for f in tqdm(os.listdir('./data')[0:100000]):
    with open('./data/' + f, 'rb') as fin:
        ds.update(pickle.load(fin).keys())

100%|██████████| 100000/100000 [02:56<00:00, 565.45it/s]


In [10]:
pattern = re.compile('\d{5}\d*')

NameError: name 're' is not defined

In [21]:
ds

{'',
 'затороторя',
 'юськ',
 'девчушечк',
 'российскийксотерап',
 'munkholm',
 'ltktubhetncz',
 'ориенттехникс',
 'авторитют',
 'manic',
 'strdispos',
 'shopv',
 'оукл',
 'sumeet',
 'yoqsp',
 'хендлинг',
 'юзелюнас',
 'выжидател',
 'макфлурр',
 'намдак',
 'пшиезжа',
 'двухсигнальн',
 'íîìèíàöèè',
 'сбякнут',
 'aromar',
 'настрйк',
 'кишечныйлечен',
 'держсекретар',
 'cbhb',
 'eineimvorjahrbegonneneuntersuchungzurrealisierungvongabor',
 'garum',
 'аверландск',
 'лудон',
 'gintautas',
 'дремучест',
 'шпирн',
 'кобъен',
 'меткост',
 'taiteilija',
 'шайдак',
 'систолічн',
 'embolicus',
 'бенфорд',
 'amsk',
 'экстрагейт',
 'dgecnbnt',
 'vosbh',
 'вячкил',
 'кейнсианс',
 'capers',
 'determinar',
 '6531',
 'върна',
 'isomer',
 'следипломн',
 'капюшен',
 'ньорд',
 'металличес',
 'шинус',
 'первородок',
 'дотт',
 'эгизаря',
 'bjdf',
 'стокбаргер',
 'alltr',
 'walher',
 'oikeaks',
 'мінусів',
 'рравн',
 'сайзмор',
 'zusammengesetzhe',
 'webrock',
 'слушаюс',
 'xhskfc',
 'ctlfilelist',
 'карпуне

In [38]:
dc.pop('57')

1

In [46]:
dc

Counter({'такой': 12,
         'варикоз': 59,
         'пигментация': 1,
         'соотношение': 1,
         'правило': 3,
         'пострадавший': 3,
         'останавливать': 1,
         'протечка': 1,
         'помощь': 5,
         'нужно': 1,
         'таблетка': 2,
         'вставание': 1,
         'затруднять': 1,
         'как': 33,
         'чрезвычайно': 2,
         'сухость': 1,
         'вполне': 1,
         'без': 3,
         'мой': 1,
         'входить': 1,
         'полечиться': 1,
         'закаливание': 1,
         'удалять': 5,
         'доступный': 1,
         'разделять': 1,
         'помимо': 1,
         'committee': 1,
         'больший': 2,
         'картинка': 1,
         'чувствительность': 1,
         'сульфат': 1,
         'использование': 9,
         'консервативный': 1,
         'assessment': 2,
         'гематома': 1,
         'анти': 1,
         'ожирение': 1,
         'хорошо': 4,
         'использовать': 6,
         'сессия': 1,
         'инфекция': 2,
 

In [43]:
arr = [1, 2, 3]

In [45]:
list(filter(lambda x: x > 2, arr))

[3]

In [47]:
for key in dc:
    print(key)
    break

такой


In [62]:
len(dict(filter(lambda x: not pattern.match(x[0]), dc.items())))

1151

In [63]:
len(dc)

1190

In [138]:
len(dc)

2288

In [8]:
stop = stopwords.words('russian')
stemmer = SnowballStemmer('russian', ignore_stopwords=True)

In [146]:
ndc = filter(lambda x: not (x[0] in stop), dc.items())
ndc = dict(map(lambda x: (stemmer.stem(x[0]), x[1]), ndc))

In [148]:
len(ndc)

2065

In [158]:
res = Counter(dc)
res.subtract(Counter(ndc))

In [160]:
dc

{'выливать': 1,
 '57': 1,
 'гипертония': 1,
 'обыкновенный': 1,
 'вафля': 1,
 'элементарный': 1,
 'такой': 28,
 'превивать': 4,
 'бороздка': 3,
 'сколько': 3,
 'момент': 4,
 'f': 3,
 'делать': 12,
 'перед': 10,
 'приболеть': 1,
 'оставлять': 7,
 'вредный': 1,
 'успевать': 2,
 'настой': 5,
 'потомство': 1,
 'потрясать': 1,
 'годиться': 1,
 'генциана': 1,
 'помощь': 1,
 'куриный': 1,
 'страница': 1,
 'видео': 1,
 'нужно': 10,
 'выход': 2,
 'таблетка': 1,
 'еженедельно': 1,
 'пасынок': 5,
 'пригодный': 1,
 'лист': 11,
 'удобрение': 5,
 'как': 55,
 'принцип': 1,
 'проветривание': 1,
 'недовольный': 1,
 'дэвид': 1,
 'знание': 2,
 'питательный': 3,
 'вполне': 1,
 'порей': 1,
 'шелуха': 1,
 'серия': 4,
 'охлаждение': 2,
 'кино': 1,
 'проращивать': 2,
 'ползучий': 1,
 'бензин': 1,
 'тлеть': 1,
 'луковый': 1,
 'удалять': 1,
 'работа': 2,
 'ассортимент': 1,
 'подобный': 3,
 'отрицательный': 2,
 'повреждать': 2,
 'сажать': 4,
 'любимый': 2,
 '0': 188,
 'камень': 1,
 'гарантировать': 2,
 'созвезди

In [177]:
stemmer.stem('му')

'му'

In [7]:
lemmatizer = Mystem()

In [23]:
_eng_chars = u"~!@#$%^&qwertyuiop[]asdfghjkl;'zxcvbnm,./QWERTYUIOP{}ASDFGHJKL:\"|ZXCVBNM<>?"
_rus_chars = u"ё!\"№;%:?йцукенгшщзхъфывапролджэячсмитьбю.ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭ/ЯЧСМИТЬБЮ,"
_trans_table = dict(zip(_eng_chars, _rus_chars))
 
def fix_layout(s):
    return u''.join([_trans_table.get(c, c) for c in s])

In [6]:
ttf = dict()
with open('total.dict', 'rb') as fin:
    ttf = pickle.load(fin)

In [77]:
f_one = set()
pattern = re.compile('\d+|[^\W\d]+')
with open('./queries.final', 'r') as fin:
    for line in fin:
        idx, line = line.split('\t')
        words = pattern.findall(line)
        
        for word in words:
            t = stemmer.stem(lemmatizer.lemmatize(word)[0])
            if not (t in ttf):
                f_one.add(word)

In [78]:
len(f_one)

27

In [79]:
f_one

{'000008',
 '000989880310',
 '12345678',
 '1800103',
 '20032',
 '21099',
 '21144',
 '21214',
 '22004',
 '250517',
 '2704482',
 '33170726515',
 '396255',
 '590624',
 '79168920892',
 '81048123799726',
 '89515200611',
 '90002',
 '926884',
 'ведь',
 'еннитсоирейг',
 'если',
 'здесь',
 'нибудь',
 'носскеибирво',
 'опять',
 'педегичесткий'}

In [67]:
ttf[stemmer.stem('datalova')]

1

In [23]:
ccc = Counter()

In [24]:
ccc['a'] = 10

In [28]:
fff = np.unique(list(map(lambda x: int(x.split('.')[0]), os.listdir('./frequences/'))))

In [29]:
fff

array([     0,      1,      2, ..., 582141, 582142, 582143])

In [14]:
gm3 = list(map(lambda x: ''.join(x), ngrams(list('hello my dear friend'), 3)))

In [15]:
cv = CountVectorizer(vocabulary=gm3)

In [23]:
cv.transform(['hel', 'llo']).toarray()

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
with open('log.txt', 'r') as fin:
    for l in fin:
        print(l)

0	SMARTJS ACADEMY АРХИТЕКТУРА JS ПРИЛОЖЕНИЙ ХАРЬКОВ



In [27]:
d3 = Counter()

In [ ]:
with open('titles.txt', 'r') as fin:
    for line in fin:
        title

In [19]:
cv = CountVectorizer(analyzer='char', ngram_range=(3, 3))

In [20]:
cv.fit(['#abcd#', '#defg#'])

CountVectorizer(analyzer='char', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(3, 3), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [21]:
cv.transform(['abcd']).toarray()

array([[0, 0, 1, 1, 0, 0, 0, 0]])

In [22]:
cv.vocabulary_

{'#ab': 0,
 '#de': 1,
 'abc': 2,
 'bcd': 3,
 'cd#': 4,
 'def': 5,
 'efg': 6,
 'fg#': 7}